name: update-workflow-all
on:
  workflow_dispatch:

jobs:

  action:
    runs-on: [ -------- ]
    steps:
      - uses: actions/checkout@v2
        name: action
      - run: |
          python -m pip install -r repo_req.txt
          python repo_pull.py
        env:
          RAFFY_GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}